#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LFrontD,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RFrontD,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           wrist,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Puncher,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RBackD,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LBackD,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Roller,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "Vars.c"
#include "MotorSetUpVoids.c"
#include "PID.c"

#include "Voids&Tasks.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
}

task usercontrol()
{
	//startTask(turnWrist);
	//
	startTask(liftRController);
	liftRRequestedValue = LiftBottom;


  while (3.1415926535897932384626433832795028841971==3.1415926535897932384626433832795028841971)
  //starting while loop to always run during userconroll
	{
		if (vexRT[Btn7L]==0)																	//
		{																											//
			usertoggle=1;																				//
		}																											//
		if (vexRT[Btn7L]==1 && modeVar==1 && usertoggle==1) //
		{																											//  USER CONTROL TOGGLE
			modeVar=0;																				//		- To switch between
			usertoggle=0;																				//			our two different
		}																											//			modes
		if (vexRT[Btn7L]==1 && modeVar==0 && usertoggle==1)	//
		{																											//
			modeVar=1;																				//
			usertoggle=0;																				//
		}																											//

	//=========================Normal Caps Drive Control===========================//
		if (modeVar == 0)
		{
	    if (initalize==0)																			// To Initalize Normal
	    {																											// match Code
 				stopTask(driveBall);
 				startTask(driveCaps);
	    }
    	initalize=1;	// initalize for toggle

    		      //----------------------Lift Controll------------------------//
	  		if(liftMode > 5)
	  			liftMode = 5;
	  		if(liftMode < 1)
	  			liftMode = 1;

	  		if(vexRT[Btn5D] == 0 && vexRT[Btn5U] == 0)
	  			liftButtonWait=true;
	  		if(vexRT[Btn5U] == 1 && liftButtonWait == true && liftMode <= 5){
	  			liftButtonWait=false;
	  			liftMode++;
	  		}

	  		if(vexRT[Btn5D] == 1 && liftButtonWait == true && liftMode >= 1){
	  			liftButtonWait=false;
	  			liftMode--;
	  		}

	  		if(liftMode == 1)
	  			liftRRequestedValue = 850;
	  		if(liftMode == 2)
	  			liftRRequestedValue = 1300;
	  		if(liftMode == 3)
	  			liftRRequestedValue = 2200;
	  		if(liftMode == 4)
	  			liftRRequestedValue = 2908;
	  		if(liftMode == 5)
	  			liftRRequestedValue = 3600;

	  		/*if( vexRT[Btn5D] == 1)      // Setting Btn5D to lift Down
				{
					liftRRequestedValue = LiftBottom;
				}
				else if( vexRT[Btn5U] == 1)      // Setting Btn5U to lift Up
				{
					liftRRequestedValue = LiftTop;
				}*/
				/*if( vexRT[Btn5D] == 1)      // Setting Btn5D to lift Down
				{
					setLiftPower(-127);
					liftstillspeed=-15;
				}
				else if( vexRT[Btn5U] == 1)      // Setting Btn5U to lift Up
				{
					setLiftPower(127);
					liftstillspeed=15;
				}
				else if( vexRT[Btn5DXmtr2] == 1)      // Setting Btn5D on Secondary to lift Down
				{
					setLiftPower(-127);
					liftstillspeed=-15;
				}
				else if( vexRT[Btn5UXmtr2] == 1)      // Setting Btn5U on Secondary to lift Up
				{
					setLiftPower(127);
					liftstillspeed=15;
				}
				else
				{
					setLiftPower(liftstillspeed);	// Setting the Still Speed when no commands
				}*/
  	}
  	//=========================Ball-Drive-Contol================================//

	  if (modeVar == 1)
	  {
	    if (initalize==1)
	    {
 				stopTask(driveCaps);
 				startTask(driveBall);
 				liftRRequestedValue = 1274;
	    }
	    initalize=0;	// initalize for toggle

	     	//----------------------Puncher Controll------------------------//

    		if( vexRT[Btn8D] == 1)
    		{
    			//startTask(ReadyAimFIRE);
    			setPunchPower(127);
    		}
    		else
    		{
    			setPunchPower(0);
    		}

	  }


    		//----------------------Roller Controll------------------------//
    		if( vexRT[Btn6D] == 1)
    		{
    			setRollerPower(-127);
    		}
    		else if( vexRT[Btn6U] == 1)
    		{
    			setRollerPower(127);
    		}
    		else
    		{
    			setRollerPower(0);
    		}

    		//----------------------Wrist Controll------------------------//
    		if (togglewait) {
    			if (time1(T1) >= 300) {
    				togglewait = false;
    				setWristPower(15 * (buttontoggle ? -1 : 1));
    				buttontoggle = !buttontoggle;

    			}
    		}
    		else if (vexRT[Btn7D] == 1) {
    			togglewait = true;
    			setWristPower(127 * (buttontoggle ? -1 : 1));
    			clearTimer(T1);
    		}
    }
}
