#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LFrontD,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RFrontD,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           wrist,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Puncher,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RBackD,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LBackD,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Roller,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "Vars.c"
#include "MotorSetUpVoids.c"

#include "Voids&Tasks.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
}

task usercontrol()
{
	//startTask(turnWrist);

  while (3.1415926535897932384626433832795028841971==3.1415926535897932384626433832795028841971)
  //starting while loop to always run during userconroll
	{
		if (vexRT[Btn7L]==0)																	//
		{																											//
			usertoggle=1;																				//
		}																											//
		if (vexRT[Btn7L]==1 && skillsVar==1 && usertoggle==1) //
		{																											//  USER CONTROL TOGGLE
			skillsVar=0;																				//		- To switch between
			usertoggle=0;																				//			our two different
		}																											//			modes
		if (vexRT[Btn7L]==1 && skillsVar==0 && usertoggle==1)	//
		{																											//
			skillsVar=1;																				//
			usertoggle=0;																				//
		}																											//

	//=========================Normal Caps Drive Control===========================//
		if (skillsVar == 0)
		{
	    if (initalize==0)																			// To Initalize Normal
	    {																											// match Code
 				stopTask(driveBall);
 				startTask(driveCaps);
	    }
    	initalize=1;	// initalize for toggle
  	}
  	//=========================Ball-Drive-Contol================================//

	  if (skillsVar == 1)
	  {
	    if (initalize==1)
	    {
 				stopTask(driveCaps);
 				startTask(driveBall);
	    }
	    initalize=0;	// initalize for toggle
	  }
	      //----------------------Lift Controll------------------------//
				if( vexRT[Btn5D] == 1)      // Setting Btn5D to lift Down
				{
					setLiftPower(-127);
					liftstillspeed=-15;
				}
				else if( vexRT[Btn5U] == 1)      // Setting Btn5U to lift Up
				{
					setLiftPower(127);
					liftstillspeed=15;
				}
				else if( vexRT[Btn5DXmtr2] == 1)      // Setting Btn5D on Secondary to lift Down
				{
					setLiftPower(-127);
					liftstillspeed=-15;
				}
				else if( vexRT[Btn5UXmtr2] == 1)      // Setting Btn5U on Secondary to lift Up
				{
					setLiftPower(127);
					liftstillspeed=15;
				}
				else
				{
					setLiftPower(liftstillspeed);	// Setting the Still Speed when no commands
				}

    		//----------------------Roller Controll------------------------//
    		if( vexRT[Btn6D] == 1)
    		{
    			setRollerPower(-127);
    		}
    		else if( vexRT[Btn6U] == 1)
    		{
    			setRollerPower(127);
    		}
    		else
    		{
    			setRollerPower(0);
    		}

    		//----------------------Puncher Controll------------------------//

    		if( vexRT[Btn8D] == 1)
    		{
    			//startTask(ReadyAimFIRE);
    			setPunchPower(127);
    		}
    		else
    		{
    			setPunchPower(0);
    		}

    		//----------------------Wrist Controll------------------------//
    		if (togglewait) {
    			if (time1(T1) >= 250) {
    				togglewait = false;
    				setWristPower(15 * (buttontoggle ? -1 : 1));
    				buttontoggle = !buttontoggle;

    			}
    		}
    		else if (vexRT[Btn7D] == 1) {
    			togglewait = true;
    			setWristPower(127 * (buttontoggle ? -1 : 1));
    			clearTimer(T1);
    		}

    		/*if(vexRT[Btn7D] == 0)
    			togglewait=true;

    		if(vexRT[Btn7D] == 1 && togglewait==true && buttontoggle==1){
    			togglewait=false;
    			buttontoggle=0;
    		}
    		else if(vexRT[Btn7D] == 1 && togglewait==true && buttontoggle==0){
    			togglewait=false;
    			buttontoggle=1;
    		}

    		startTask(turnWrist);*/
  	}
}
